### ISSUE TITLE
user-service-contract-tests will not pass due to PROD_VERSION

### ISSUE THREAD

**Issue by devtester-ro** [tinexw/cdc-with-pact#9]
PROD_VERSION returned is

git checkout Pacticipant version not found
error: pathspec 'Pacticipant' did not match any file(s) known to git.
error: pathspec 'version' did not match any file(s) known to git.
error: pathspec 'not' did not match any file(s) known to git.
error: pathspec 'found' did not match any file(s) known to git.

**Comment by tinexw** [comment]
There is an initial dead lock because both services check that they can deploy and neither can because the other wasn't yet. The `user-service-contract-tests` job requires that there is a prod version available.

The easiest way to fix it is to
- run `messaging-app-build`
- manually tag the consumer with `prod`: `./pact-broker create-version-tag -a messaging-app -b http://pact_broker -e <version> -t prod`
- manually tag the provider with `prod`: `./pact-broker create-version-tag -a user-service -b http://pact_broker -e <version> -t prod`
